project_id = "fejnevxardxejdvjbipc"

[functions.send-notification-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
